/*─────────────────────────────────────────────────────────────
  RECHARGE — BURNOUT RECOVERY & ENERGY RESTORATION PLATFORM
  fp-courses.js — Extended Recovery Program Library
  Loads after inline scripts — appends to window.FP_COURSE.modules
─────────────────────────────────────────────────────────────*/
(function(){
'use strict';
if(!window.FP_COURSE){window.FP_COURSE={modules:[]};}

/* ═══════════════════════════════════════════════════════════
   PROGRAM 1 — BURNOUT RESET PROGRAM
   Module IDs: br_m1 – br_m5
═══════════════════════════════════════════════════════════ */
var BURNOUT_RESET_MODULES = [
  {
    id:'br_m1',n:1,emoji:'🌱',courseId:'burnout-reset',courseName:'Burnout Reset Program',
    name:'Phase 1 — Foundations of Recovery',
    desc:'Understand burnout deeply, learn how your nervous system works, and lay the groundwork for sustainable recovery.',
    lessons:[
      {id:'br_m1_l1',name:'Understanding Burnout',desc:'Recognise the stages of burnout and what your nervous system needs',xp:50,tip:'Burnout is a physiological state — not a personal failure. Rest is the first medicine.',
       content:`<h3>What Burnout Actually Is</h3><p>Burnout is not simply tiredness or stress. It is a state of chronic depletion — emotional, cognitive, and physical — caused by sustained demands that exceed your capacity to recover. The World Health Organisation classifies it as an occupational phenomenon with three core dimensions.</p><h4>The Three Dimensions of Burnout</h4><ul><li><strong>Exhaustion:</strong> Feeling drained and depleted — unable to generate energy even after rest.</li><li><strong>Cynicism / Detachment:</strong> Emotional distance from work, life, or relationships that once had meaning.</li><li><strong>Reduced Efficacy:</strong> A sense that what you do doesn't matter and that you're no longer capable.</li></ul><h4>The Burnout Progression</h4><ol><li><strong>The Honeymoon Phase:</strong> High commitment, high energy — overlooking early warning signs.</li><li><strong>Onset of Stress:</strong> Physical and emotional symptoms start. Productivity compensates.</li><li><strong>Chronic Stress:</strong> Symptoms become persistent. Social withdrawal begins.</li><li><strong>Burnout:</strong> Full depletion — emotional numbing, physical symptoms, inability to function.</li><li><strong>Habitual Burnout:</strong> Burnout becomes the baseline state without intervention.</li></ol><h4>Your Recovery Starting Point</h4><p>Understanding which stage you're in is important — not to label yourself, but to calibrate how much time and gentleness your recovery will need. Severe burnout requires 12–18 months of intentional recovery. Mild-moderate may improve in 3–6 months. Both timelines require the same first step: stop trying to recover faster than your nervous system allows.</p><div class="lesson-quiz"><h4>Reflection Check-In</h4><p>Which dimension of burnout resonates most with where you are right now?</p><div class="quiz-options"><button class="qo" data-correct="true">Exhaustion — I feel constantly drained even after rest</button><button class="qo" data-correct="true">Cynicism — I feel disconnected from things that used to matter</button><button class="qo" data-correct="true">Reduced efficacy — I doubt my ability and feel nothing I do matters</button></div></div>`},
      {id:'br_m1_l2',name:'The Stress Response Cycle',desc:'How stress builds and how to complete the cycle to release it',xp:50,tip:'Completing the stress cycle — not just removing the stressor — is what allows recovery.',
       content:`<h3>Why You Still Feel Stressed After the Stressor Has Gone</h3><p>Your body's stress response was designed for short-term physical threats — not the sustained psychological pressures of modern life. Understanding this distinction is foundational to recovery.</p><h4>The Stress Cycle</h4><p>When you encounter a stressor, your body activates a cascade: cortisol and adrenaline rise, your heart rate increases, muscles tense, digestion slows. This is the activation phase. In nature, this is followed by physical action — running, fighting — which completes the cycle and returns the body to baseline.</p><p>In modern burnout, the stressor (an email, a deadline, a conflict) activates the cycle — but there is no physical completion. The biology remains activated even after the stressor passes. Over time, these incomplete cycles accumulate.</p><h4>How to Complete the Cycle</h4><ul><li><strong>Physical movement:</strong> Even a 20-minute walk signals cycle completion to your nervous system.</li><li><strong>Breathwork:</strong> Extended exhale activates the parasympathetic system — the physiological off-switch.</li><li><strong>Creative expression:</strong> Drawing, writing, music — any expressive act that discharges the emotional charge.</li><li><strong>Connection:</strong> Safe, authentic human connection (even briefly) is one of the most powerful cycle completers.</li><li><strong>Laughter or crying:</strong> Both are natural biological mechanisms for completing emotional stress cycles.</li></ul><h4>Practice</h4><p>After any stressful event today, choose one cycle-completing activity from the list above. Do it within 90 minutes of the stressor. Notice what shifts in your body.</p><div class="lesson-quiz"><h4>Knowledge Check</h4><p>Why does removing a stressor not automatically make you feel better?</p><div class="quiz-options"><button class="qo" data-correct="false">Because more stressors always follow immediately after</button><button class="qo" data-correct="true">Because the biological stress response cycle needs to be actively completed, not just paused</button><button class="qo" data-correct="false">Because stress is purely psychological and takes time to forget</button></div></div>`},
      {id:'br_m1_l3',name:'Attention & Presence',desc:'Train your focus back to the present moment to reduce cognitive overload',xp:60,tip:'Five minutes of deliberate presence rewires your attention more than an hour of passive rest.',
       content:`<h3>Burnout and the Attention System</h3><p>One of the least-discussed effects of burnout is what it does to attention. When the nervous system is chronically overloaded, the prefrontal cortex — the region responsible for focused attention, decision-making, and emotional regulation — becomes under-resourced. This is why burnout so often feels like brain fog, inability to concentrate, and a constant sense of being overwhelmed by small decisions.</p><h4>Attention Restoration Theory</h4><p>Research by Rachel and Stephen Kaplan found that directed attention — the kind used in work, problem-solving, and decision-making — fatigues over time and requires active restoration. Passive rest (scrolling, watching TV) does not restore directed attention. Active restoration does.</p><h4>Attention Restoration Practices</h4><ul><li><strong>Nature exposure:</strong> Even 10 minutes looking at trees measurably reduces mental fatigue.</li><li><strong>Single-tasking:</strong> Complete one task at a time with full attention — even if briefly.</li><li><strong>Sensory grounding:</strong> Bringing awareness to physical sensations anchors attention in the present.</li><li><strong>Open monitoring meditation:</strong> Noticing thoughts without engaging them — a resting mode for the attention system.</li></ul><h4>Today's Practice</h4><p>Set a timer for 5 minutes. Sit quietly with no screen. Notice five things you can see, four you can touch, three you can hear. That's it. That is a full attention restoration session.</p><div class="lesson-quiz"><h4>Knowledge Check</h4><p>Which of these actively restores directed attention?</p><div class="quiz-options"><button class="qo" data-correct="false">Scrolling social media for 30 minutes</button><button class="qo" data-correct="true">Sitting in a natural environment and allowing your attention to wander freely</button><button class="qo" data-correct="false">Sleeping for 10 hours</button></div></div>`},
      {id:'br_m1_l4',name:'Rest vs. Recovery',desc:'Why passive rest often is not enough — and what true recovery looks like',xp:60,tip:'Sleep refuels you. Active recovery restores you. Both are non-negotiable.',
       content:`<h3>The Difference That Changes Everything</h3><p>Most people in burnout believe they need more rest. They are partly right — but the distinction between rest and recovery is one of the most important in this entire program.</p><h4>Rest</h4><p>Rest is the absence of activity. Sleep is the deepest form of rest. During sleep, your body repairs tissue, consolidates memory, and clears metabolic waste from the brain. Rest is essential. But rest alone does not complete stress cycles, restore emotional capacity, or rebuild depleted meaning.</p><h4>Recovery</h4><p>Recovery is an active process. It involves deliberately doing things that restore what burnout has depleted — not just stopping what depleted it. Recovery practices include:</p><ul><li>Breathwork and nervous system regulation</li><li>Meaningful connection with safe people</li><li>Physical movement that completes stress cycles</li><li>Creative or expressive activities</li><li>Experiences of joy, awe, or beauty</li><li>Purposeful stillness (as distinct from collapse)</li></ul><h4>Why This Matters</h4><p>Many people in burnout report sleeping 9–10 hours and still feeling exhausted. This is because sleep addresses physical restoration but not the accumulated emotional and nervous system debt. Recovery addresses both.</p><div class="lesson-quiz"><h4>Knowledge Check</h4><p>Someone is sleeping 9 hours a night but still feeling depleted. What is most likely missing?</p><div class="quiz-options"><button class="qo" data-correct="false">They need more sleep — 9 hours is not enough</button><button class="qo" data-correct="true">Active recovery practices that address emotional and nervous system restoration</button><button class="qo" data-correct="false">They need stimulants to increase energy during the day</button></div></div>`},
      {id:'br_m1_l5',name:'Nervous System Basics',desc:'Sympathetic vs parasympathetic — learning to regulate your own state',xp:80,tip:'Your exhale activates the parasympathetic system. Slow it down intentionally.',
       content:`<h3>Your Nervous System Is the Recovery Organ</h3><p>Everything about burnout recovery comes back to the autonomic nervous system — specifically, the balance between its two primary branches.</p><h4>The Sympathetic Branch — "Fight or Flight"</h4><p>Activated by threat, demand, uncertainty, and stress. Increases heart rate, cortisol, and muscle tension. Narrows attention to immediate problems. This branch evolved for short-term emergencies — not the sustained activation that chronic stress creates. In burnout, this branch is chronically over-activated.</p><h4>The Parasympathetic Branch — "Rest and Digest"</h4><p>Activated by safety, stillness, slow breathing, warmth, and connection. Lowers heart rate, promotes digestion, and enables deep sleep. This is the recovery branch. Your ability to access it is the foundation of burnout recovery.</p><h4>The Vagus Nerve</h4><p>The primary parasympathetic pathway is the vagus nerve — the longest nerve in the body, connecting the brain to the gut, lungs, and heart. Stimulating the vagus nerve directly activates recovery mode. The most accessible way: slow your exhale.</p><h4>Physiological Sigh</h4><p>One of the fastest ways to shift from sympathetic to parasympathetic activation is the physiological sigh: double inhale through the nose (two short sniffs), then one long, slow exhale through the mouth. Research at Stanford shows this reduces physiological arousal faster than any other single breath pattern.</p><div class="lesson-quiz"><h4>Knowledge Check</h4><p>Which part of the breath most directly activates the parasympathetic (recovery) state?</p><div class="quiz-options"><button class="qo" data-correct="false">A deep, fast inhale</button><button class="qo" data-correct="true">A slow, extended exhale</button><button class="qo" data-correct="false">Holding the breath at the top of an inhale</button></div></div>`}
    ]
  },
  {
    id:'br_m2',n:2,emoji:'🎯',courseId:'burnout-reset',courseName:'Burnout Reset Program',
    name:'Phase 2 — Energy Restoration',
    desc:'Audit your energy, build boundary skills, establish pacing habits, and restore your sleep quality.',
    lessons:[
      {id:'br_m2_l1',name:'Energy Audit',desc:'Identify what drains vs restores your energy across all life areas',xp:60,tip:'What depletes and what restores is deeply personal. Track it honestly for 7 days.',
       content:`<h3>Your Personal Energy Landscape</h3><p>Before you can restore your energy, you need to understand where it is going. Most people in burnout can identify the big obvious drains — but the cumulative effect of small, invisible drains is often what tips the system into collapse.</p><h4>The Energy Audit Framework</h4><p>Over the next 7 days, notice and record each significant activity or interaction with a simple +/– rating: does it give you energy or take it? Include: work tasks, people, environments, commutes, social obligations, physical activities, digital consumption, food and sleep quality, emotional events.</p><h4>Energy Categories</h4><ul><li><strong>High Drain / Low Value:</strong> Eliminate or reduce these first.</li><li><strong>High Drain / High Value:</strong> These are necessary — build recovery around them.</li><li><strong>Low Drain / Low Value:</strong> These are often invisible time-fillers — consider releasing them.</li><li><strong>Low Drain / High Value:</strong> Protect these fiercely. Increase them where possible.</li></ul><h4>The Recovery Implication</h4><p>An energy audit is not a productivity exercise. It is a compassion exercise — you are trying to understand what your system needs, not optimise output. What surprises you most about your list?</p><div class="lesson-quiz"><h4>Reflection</h4><p>Which energy category have you been spending the most time in?</p><div class="quiz-options"><button class="qo" data-correct="true">High Drain — whether or not it's high value</button><button class="qo" data-correct="true">Low Drain / Low Value — invisible time-fillers</button><button class="qo" data-correct="true">High Value restorers — but not enough of them</button></div></div>`},
      {id:'br_m2_l2',name:'Boundary Setting Foundations',desc:'Build the ability to say no without guilt',xp:80,tip:'Every boundary you hold protects a piece of your energy that you cannot replace.',
       content:`<h3>Boundaries Are an Energy Management Tool</h3><p>The inability to say no is one of the most significant contributors to burnout — and one of the hardest patterns to change, because it is almost always tied to deep beliefs about worth, safety, and belonging.</p><h4>Why Saying No Feels Dangerous</h4><p>For many people in burnout, saying no carries an unconscious threat: rejection, conflict, or the belief that your value depends on what you do for others. These beliefs are worth examining — not to judge them, but to understand why every yes costs more than it should.</p><h4>The Three Types of Limit</h4><ul><li><strong>Time limits:</strong> What you will and will not commit your time to.</li><li><strong>Energy limits:</strong> How much you will give in any interaction or context.</li><li><strong>Emotional limits:</strong> What topics, behaviours, or dynamics you will not engage with.</li></ul><h4>Starting Small</h4><p>You do not need to transform your boundary capacity overnight. Start with one small, low-stakes no per day for the next week. It does not need to be explained or justified. Notice what happens in your body when you hold it — and what happens when you don't.</p><div class="lesson-quiz"><h4>Knowledge Check</h4><p>What is the primary purpose of a limit in the context of burnout recovery?</p><div class="quiz-options"><button class="qo" data-correct="false">To avoid responsibility and reduce workload permanently</button><button class="qo" data-correct="true">To protect finite energy reserves so recovery is actually possible</button><button class="qo" data-correct="false">To communicate that you are too stressed to help others</button></div></div>`},
      {id:'br_m2_l3',name:'Recovery Pacing',desc:'Structure your days around energy capacity, not task lists',xp:80,tip:'Pace yourself like a long-distance runner — sustainable rhythm beats sprinting.',
       content:`<h3>The Pacing Principle</h3><p>One of the most common recovery mistakes is following the same boom-bust pattern that caused burnout in the first place: feel slightly better → immediately fill the space with activity → crash again. Recovery pacing interrupts this pattern.</p><h4>The Boom-Bust Cycle</h4><ol><li>Low energy → forced rest</li><li>Energy slightly improves → overcommit again</li><li>Crash — often worse than before</li></ol><p>This cycle is exhausting and demoralising — but it is extremely common. Recognising it without self-judgement is the first step.</p><h4>Pacing for Recovery</h4><ul><li><strong>Plan based on consistent, sustainable activity</strong> — not what you can do on your best day.</li><li><strong>Build in rest before you need it,</strong> not only when you collapse.</li><li><strong>Use the envelope:</strong> Stay within your energy limit even when you feel good — especially when you feel good.</li><li><strong>30% rule:</strong> When you feel capable of doing 100%, do 70%. The remaining 30% is recovery capital.</li></ul><h4>Practice</h4><p>For one week, plan your day around your realistic energy capacity — not your aspirational to-do list. What has to be non-negotiable? What is optional? What can wait or be delegated?</p><div class="lesson-quiz"><h4>Knowledge Check</h4><p>What does the 30% rule mean in recovery pacing?</p><div class="quiz-options"><button class="qo" data-correct="false">Only do 30% of what you normally do, permanently</button><button class="qo" data-correct="true">When you feel capable of doing 100%, stop at 70% to preserve recovery capital</button><button class="qo" data-correct="false">Rest for 30% of your working day</button></div></div>`},
      {id:'br_m2_l4',name:'Micro-Recovery Habits',desc:'Small daily practices that prevent energy depletion from accumulating',xp:60,tip:'A 3-minute decompression break every 90 minutes prevents the accumulation that causes crashes.',
       content:`<h3>The Power of Small</h3><p>The research on recovery consistently shows that brief, frequent recovery periods are more effective than longer, infrequent ones. This is counterintuitive — most people believe they need a holiday or a week off. But your nervous system recovers in micro-cycles throughout the day.</p><h4>Ultradian Rhythms</h4><p>Your brain naturally cycles through states of higher and lower alertness approximately every 90–120 minutes. At the end of each cycle, your system signals for a short recovery period — often experienced as restlessness, loss of focus, or a desire to snack or check your phone. Honouring these signals with a brief recovery break prevents the accumulation of stress that leads to afternoon crashes and evening depletion.</p><h4>Micro-Recovery Practices (2–5 minutes)</h4><ul><li>Step outside and look at the sky for 2 minutes</li><li>Three slow breath cycles — double-length exhale</li><li>Brief body scan — relax jaw, shoulders, hands</li><li>Drink water mindfully (away from the screen)</li><li>Write one sentence about how you are currently feeling</li></ul><h4>Implementation</h4><p>Set a gentle alarm every 90 minutes. When it sounds, stop for 2–3 minutes and choose any practice from the list. That is all. This one habit, consistently practised, is one of the highest-leverage changes in this entire program.</p><div class="lesson-quiz"><h4>Knowledge Check</h4><p>How often does the brain's natural ultradian cycle signal for recovery?</p><div class="quiz-options"><button class="qo" data-correct="false">Once per day — at lunchtime</button><button class="qo" data-correct="true">Approximately every 90–120 minutes throughout the day</button><button class="qo" data-correct="false">Only when you feel tired or unwell</button></div></div>`},
      {id:'br_m2_l5',name:'Sleep Optimisation',desc:'Evidence-based sleep hygiene tailored for those in burnout',xp:70,tip:'Consistent sleep and wake times matter more than total hours for nervous system recovery.',
       content:`<h3>Sleep as the Foundation of Recovery</h3><p>Sleep is non-negotiable in burnout recovery. But many people in burnout find that sleep becomes disrupted — they are exhausted but unable to fall asleep, or they sleep long hours and still wake unrefreshed. Understanding why helps.</p><h4>Why Burnout Disrupts Sleep</h4><p>Chronic cortisol elevation — the hallmark of burnout — directly disrupts sleep architecture. Cortisol should be low at night, triggering melatonin release. In burnout, cortisol remains elevated in the evening, making it difficult to fall asleep and reducing time in the deep, restorative sleep stages.</p><h4>Burnout-Specific Sleep Hygiene</h4><ul><li><strong>Consistent wake time:</strong> Your most powerful sleep regulator. Set it and hold it — even on weekends.</li><li><strong>Light exposure in the morning:</strong> 10 minutes of outdoor light within 30 minutes of waking anchors your circadian rhythm.</li><li><strong>Cortisol wind-down:</strong> Avoid stimulating content, difficult conversations, and work for 60–90 minutes before bed.</li><li><strong>Temperature:</strong> A cool bedroom (16–18°C) significantly improves deep sleep quality.</li><li><strong>The 20-minute rule:</strong> If you cannot sleep after 20 minutes, leave bed. Do something calm. Return when sleepy.</li><li><strong>No alcohol:</strong> Alcohol suppresses REM sleep — the stage most critical for emotional processing and burnout recovery.</li></ul><div class="lesson-quiz"><h4>Knowledge Check</h4><p>Why does burnout often disrupt sleep even when you feel exhausted?</p><div class="quiz-options"><button class="qo" data-correct="false">Burnout makes you need less sleep</button><button class="qo" data-correct="true">Elevated cortisol from chronic stress disrupts melatonin release and deep sleep stages</button><button class="qo" data-correct="false">The mind becomes too active to allow sleep during recovery</button></div></div>`}
    ]
  },
  {
    id:'br_m3',n:3,emoji:'🌍',courseId:'burnout-reset',courseName:'Burnout Reset Program',
    name:'Phase 3 — Stress Resilience',
    desc:'Map your stress triggers, build regulated responses, reduce cognitive load, and rebuild self-trust.',
    lessons:[
      {id:'br_m3_l1',name:'Identifying Stress Triggers',desc:'Mapping your personal stress landscape — people, situations, thoughts',xp:70,tip:'Triggers are not problems to fix immediately. Start by noticing them without judgment.',
       content:`<h3>Your Personal Stress Landscape</h3><p>Not all stress is created equal. Understanding your specific triggers — the particular people, situations, environments, and thought patterns that activate your stress response — gives you agency in a way that generic stress management advice never can.</p><h4>Categories of Triggers</h4><ul><li><strong>Environmental:</strong> Noise, clutter, screens, lighting, crowds.</li><li><strong>Interpersonal:</strong> Specific people, communication styles, conflict, uncertainty in relationships.</li><li><strong>Cognitive:</strong> Perfectionism thoughts, catastrophising, self-criticism loops.</li><li><strong>Situational:</strong> Deadlines, ambiguity, loss of control, transitions.</li><li><strong>Physiological:</strong> Hunger, dehydration, poor sleep, caffeine.</li></ul><h4>The Trigger Mapping Exercise</h4><p>For one week, keep a brief log. Each time you notice your stress response activating — tension, irritability, brain fog, overwhelm — write: (1) what triggered it, (2) what category it belongs to, (3) how long the response lasted.</p><p>At the end of the week, you will have your personal stress map — not to eliminate every trigger, but to approach them with awareness rather than automatic reaction.</p><div class="lesson-quiz"><h4>Reflection</h4><p>Which trigger category do you encounter most frequently?</p><div class="quiz-options"><button class="qo" data-correct="true">Environmental — sensory overload, clutter, noise</button><button class="qo" data-correct="true">Interpersonal — specific people or relationship dynamics</button><button class="qo" data-correct="true">Cognitive — perfectionism, self-critical thought loops</button></div></div>`},
      {id:'br_m3_l2',name:'Regulated Response Training',desc:'Practising pause and respond — not react — in high-pressure moments',xp:80,tip:'One conscious breath before responding changes your entire stress trajectory.',
       content:`<h3>The Space Between Stimulus and Response</h3><p>Viktor Frankl wrote: "Between stimulus and response, there is a space. In that space is our power to choose our response." Regulated response training is the practice of expanding that space.</p><h4>Why We React Instead of Respond</h4><p>When the stress response is activated, the amygdala — the brain's threat-detection centre — essentially hijacks the prefrontal cortex. Rational decision-making narrows. This is why we say and do things under stress that we would not do in a calmer state. Recovery does not eliminate this — but it makes the window shorter and the space larger.</p><h4>The STOP Technique</h4><ul><li><strong>S — Stop:</strong> Pause whatever you are doing.</li><li><strong>T — Take a breath:</strong> One slow breath, long exhale. This interrupts the physiological cascade.</li><li><strong>O — Observe:</strong> Notice your physical sensations, thoughts, and emotions without judging them.</li><li><strong>P — Proceed:</strong> Choose a response with intention rather than react automatically.</li></ul><h4>Practice</h4><p>Apply STOP to one situation today — any moment where you feel yourself beginning to react. It takes less than 30 seconds. Notice what changes when you do.</p><div class="lesson-quiz"><h4>Knowledge Check</h4><p>What does taking one slow breath before responding physiologically achieve?</p><div class="quiz-options"><button class="qo" data-correct="false">It shows others that you are calm and in control</button><button class="qo" data-correct="true">It activates the parasympathetic system, reducing amygdala dominance and creating space for reasoned response</button><button class="qo" data-correct="false">It delays the conversation long enough for the trigger to pass</button></div></div>`},
      {id:'br_m3_l3',name:'Reducing Cognitive Overload',desc:'Decluttering mental load: decisions, commitments and information noise',xp:80,tip:'Every open loop in your mind costs energy. Write it down — clear the RAM.',
       content:`<h3>The Mental Load Problem</h3><p>The human brain can hold approximately 7 (± 2) items in working memory at once. Modern life routinely asks far more of it. In burnout, cognitive overload is one of the primary drivers of exhaustion — the constant background processing of unresolved tasks, decisions, commitments, and worries consumes enormous energy.</p><h4>Open Loops</h4><p>David Allen coined the term "open loop" for any commitment, task, or item of concern that is sitting in your mind unresolved. Each open loop requires a small but continuous allocation of cognitive resources to track. A mind full of open loops is a mind that cannot rest — even during sleep.</p><h4>Cognitive Offloading</h4><p>The solution is not to resolve every loop immediately — it is to move them out of your mind and into a reliable external system. This is cognitive offloading.</p><ul><li>Write down every task, worry, and commitment on paper (not a screen).</li><li>Assign each one to: do, delegate, defer, or drop.</li><li>Capture anything you are trying to remember in one trusted place.</li><li>Do a "brain dump" every morning — 5 minutes of writing everything on your mind.</li></ul><div class="lesson-quiz"><h4>Knowledge Check</h4><p>Why does writing tasks and worries on paper help reduce mental fatigue?</p><div class="quiz-options"><button class="qo" data-correct="false">It makes tasks feel more official and important</button><button class="qo" data-correct="true">It closes open loops in working memory, freeing cognitive resources for rest and recovery</button><button class="qo" data-correct="false">It creates accountability that reduces procrastination</button></div></div>`},
      {id:'br_m3_l4',name:'Social Recovery',desc:'Navigating relationships and communication during burnout recovery',xp:70,tip:'One honest conversation beats ten performative ones.',
       content:`<h3>Burnout and Connection</h3><p>Burnout often creates a painful paradox: the very thing that helps recovery most — authentic human connection — becomes something that feels impossible to access. Social exhaustion, the fear of being a burden, and the energy cost of performing "okay" can lead to increasing isolation.</p><h4>Social Energy in Burnout</h4><p>Not all social interaction is restorative. During burnout, it is important to distinguish between:</p><ul><li><strong>Draining interactions:</strong> Those requiring performance, emotional management of others, or masking of your true state.</li><li><strong>Neutral interactions:</strong> Brief, low-demand contact that does not tax your system.</li><li><strong>Restorative interactions:</strong> Authentic, safe connections where you can be honest without managing the other person's reaction.</li></ul><h4>Protecting Your Social Energy</h4><ul><li>Identify one or two genuinely safe people in your life. These are people with whom you do not have to perform.</li><li>Reduce performative social commitments where possible during recovery.</li><li>Be honest with safe people about where you are — you do not have to explain everything, but "I'm exhausted and recovering" is enough.</li><li>Brief, authentic contact (a voice note, a short walk) is more restorative than a long social obligation.</li></ul><div class="lesson-quiz"><h4>Knowledge Check</h4><p>Which type of social interaction is most restorative during burnout recovery?</p><div class="quiz-options"><button class="qo" data-correct="false">Large social gatherings that provide distraction from recovery</button><button class="qo" data-correct="true">Brief, authentic connection with safe people where no performance is required</button><button class="qo" data-correct="false">Any social interaction, as connection is always restorative</button></div></div>`},
      {id:'br_m3_l5',name:'Confidence & Self-Trust Rebuilding',desc:'Reclaiming your sense of capability after burnout erosion',xp:80,tip:'Confidence returns through action, not through waiting to feel ready.',
       content:`<h3>What Burnout Does to Self-Trust</h3><p>Burnout does not only deplete energy — it erodes identity. Many people emerge from burnout no longer trusting their own judgement, capacity, or worth. This is one of the most painful and least-discussed aspects of recovery.</p><h4>Why This Happens</h4><p>Sustained high-demand environments often require you to override your own needs, signals, and limits repeatedly. Over time, this trains you to distrust your own perceptions. When burnout finally forces you to stop, the evidence — that you "failed" to keep going — can feel like proof of inadequacy rather than proof of a system that was pushed too far.</p><h4>Rebuilding Through Small Wins</h4><ul><li><strong>Complete small things:</strong> Any completed action — however minor — rebuilds the neural pathway of efficacy.</li><li><strong>Write it down:</strong> At the end of each day, write one thing you did. Not achieved — did. Washed the dishes counts.</li><li><strong>Honour your signals:</strong> When you need rest and you take it, you are building self-trust. That is evidence of a functioning system, not a failure.</li><li><strong>Self-compassion as medicine:</strong> Research by Dr Kristin Neff consistently shows self-compassion — treating yourself as you would a struggling friend — accelerates recovery from failure and setback more than self-criticism.</li></ul><div class="lesson-quiz"><h4>Knowledge Check</h4><p>What rebuilds self-trust and confidence most effectively after burnout?</p><div class="quiz-options"><button class="qo" data-correct="false">Waiting until you feel confident before taking action</button><button class="qo" data-correct="true">Completing small, consistent actions and acknowledging them — building evidence of capability over time</button><button class="qo" data-correct="false">Pushing through difficult tasks to prove you are still capable</button></div></div>`}
    ]
  },
  {
    id:'br_m4',n:4,emoji:'🏠',courseId:'burnout-reset',courseName:'Burnout Reset Program',
    name:'Phase 4 — Sustainable Wellbeing',
    desc:'Design recovery routines, optimise your environment, prevent relapse, and architect a calmer life.',
    lessons:[
      {id:'br_m4_l1',name:'Recovery Routine Architecture',desc:'Design a morning and evening routine that supports healing',xp:60,tip:'Bookend your day. What you do in the first and last 30 minutes shapes everything in between.',
       content:`<h3>The Power of Bookends</h3><p>The most important periods of your day for nervous system regulation are the first 30 minutes after waking and the last 30 minutes before sleep. How you use these windows either supports recovery or undermines it — regardless of what happens in between.</p><h4>Morning Routine for Recovery</h4><ul><li><strong>No screens for 30 minutes after waking.</strong> Starting with email or news activates the stress response before your nervous system has fully transitioned from sleep.</li><li><strong>Natural light within 30 minutes.</strong> Anchors circadian rhythm and cortisol timing.</li><li><strong>Slow activation.</strong> One breathwork practice, gentle movement, or quiet reflection before the day's demands begin.</li><li><strong>One intention.</strong> Not a task list — one intention for how you want to move through the day.</li></ul><h4>Evening Routine for Recovery</h4><ul><li><strong>A clear wind-down signal.</strong> Same activity, same time — signals to your nervous system that the day is ending.</li><li><strong>Screen reduction 60–90 minutes before bed.</strong></li><li><strong>Process the day briefly.</strong> Write three things that happened and one thing you are grateful for. This closes open loops and shifts the emotional register before sleep.</li></ul><div class="lesson-quiz"><h4>Knowledge Check</h4><p>Why is checking email or news immediately after waking counterproductive for recovery?</p><div class="quiz-options"><button class="qo" data-correct="false">It wastes time that could be used for exercise</button><button class="qo" data-correct="true">It activates the stress response before the nervous system has fully transitioned from sleep, setting a reactive tone for the day</button><button class="qo" data-correct="false">It creates too much information to process before breakfast</button></div></div>`},
      {id:'br_m4_l2',name:'Safe Space Creation',desc:'Build a physical and mental environment that supports your nervous system',xp:70,tip:'Your environment either supports recovery or disrupts it. Audit it with fresh eyes.',
       content:`<h3>The Environment as Recovery Input</h3><p>Your physical environment communicates with your nervous system constantly — through light levels, noise, clutter, temperature, and aesthetic cues. In a state of burnout, an unsupportive environment can sustain the stress response even during periods of rest.</p><h4>Physical Environment Audit</h4><ul><li><strong>Light:</strong> Harsh overhead lighting activates alertness. Warm, lower light supports parasympathetic activity in the evening.</li><li><strong>Clutter:</strong> Visual disorder is consistently associated with elevated cortisol. You don't need minimalism — but one clear, calm space matters.</li><li><strong>Noise:</strong> Unpredictable noise is far more stressful than consistent background sound. Earplugs, headphones, or natural sound can shift your state significantly.</li><li><strong>Temperature:</strong> A slightly cool environment supports both focus and sleep.</li><li><strong>Nature cues:</strong> Plants, natural light, and views of greenery measurably reduce stress hormones.</li></ul><h4>The Recovery Corner</h4><p>Designate one space — even just a chair — as your recovery space. Use it only for rest, breathwork, or quiet reflection. Over time, entering that space becomes a cue for your nervous system to shift into recovery mode.</p><div class="lesson-quiz"><h4>Knowledge Check</h4><p>Why does visual clutter contribute to burnout?</p><div class="quiz-options"><button class="qo" data-correct="false">It distracts from productive work</button><button class="qo" data-correct="true">It is consistently associated with elevated cortisol — the chronic stress hormone</button><button class="qo" data-correct="false">It signals that you are not organised enough to recover</button></div></div>`},
      {id:'br_m4_l3',name:'Independent Recovery Practice',desc:'Building self-guided habits that work even when you are feeling low',xp:80,tip:'Start with what takes less than 2 minutes. Habit stacking makes recovery sustainable.',
       content:`<h3>Recovery That Doesn't Require You to Feel Good First</h3><p>One of the cruelest features of burnout is that the people who most need recovery practices are often the least resourced to initiate them. The practices that would help feel impossible precisely when they are most needed.</p><h4>The 2-Minute Rule</h4><p>Any recovery habit that takes less than 2 minutes is almost always accessible — even on the worst days. This is not about being ambitious. It is about being consistent. A 2-minute breathing practice every day for 30 days is more powerful than a 30-minute session once a week.</p><h4>Habit Stacking for Recovery</h4><p>Attach recovery practices to existing habits so they require no willpower to initiate. Examples:</p><ul><li>After I make tea, I do 5 slow breaths before checking my phone.</li><li>Before I start the car, I do one body scan.</li><li>When I sit down to eat, I put my phone away and eat mindfully.</li><li>Before I open my laptop, I write one sentence about how I feel.</li></ul><h4>Emergency Recovery Stack</h4><p>For your lowest days, have a 3-practice stack ready that requires almost nothing: (1) one slow breath, (2) a glass of water, (3) one kind thought toward yourself. That is your floor. Everything above it is a bonus.</p><div class="lesson-quiz"><h4>Knowledge Check</h4><p>What is the primary purpose of the 2-minute rule for recovery habits?</p><div class="quiz-options"><button class="qo" data-correct="false">To keep recovery sessions short so they don't take up too much time</button><button class="qo" data-correct="true">To ensure practices remain accessible even on the worst days when motivation and energy are lowest</button><button class="qo" data-correct="false">Because longer practices are not effective for burnout recovery</button></div></div>`},
      {id:'br_m4_l4',name:'Reducing Burnout Relapse Risks',desc:'Recognise early warning signs and build your personal prevention plan',xp:70,tip:'Know your early signals. Burnout rarely arrives suddenly — it builds in layers.',
       content:`<h3>The Relapse Reality</h3><p>Burnout relapse — returning to burnout after recovery has begun — is common. It does not mean you failed. It means the patterns that led to burnout in the first place have been partially reactivated. Understanding your personal early warning signs is the most effective prevention tool available.</p><h4>Burnout Warning Signs — Personal Audit</h4><p>For most people, burnout returns in a recognisable sequence. Common early signals include:</p><ul><li>Sleep quality worsening before exhaustion is felt</li><li>Increasing cynicism or emotional flatness</li><li>Skipping recovery practices "just this once"</li><li>Feeling indispensable — difficulty delegating or stepping back</li><li>Physical symptoms: tension headaches, digestive changes, increased illness</li><li>Reduced joy in things that usually restore you</li></ul><h4>Your Personal Warning System</h4><p>Write your top 3 early warning signs — the specific, personal signals that precede your stress escalation. Then write a single "if/then" plan: "If I notice [signal], I will [one recovery action]." This pre-committed response dramatically increases the chance of catching relapse early.</p><div class="lesson-quiz"><h4>Knowledge Check</h4><p>When is the best time to act on early warning signs of burnout relapse?</p><div class="quiz-options"><button class="qo" data-correct="false">When exhaustion becomes severe enough to impact work performance</button><button class="qo" data-correct="true">At the earliest possible signal — before the cascade fully activates</button><button class="qo" data-correct="false">After consulting with a doctor about the symptoms</button></div></div>`},
      {id:'br_m4_l5',name:'Calm Life Architecture',desc:'Redesign commitments, environment and habits for long-term calm',xp:70,tip:'Simplify before you optimise. Less is almost always more during recovery.',
       content:`<h3>Designing for Calm</h3><p>Recovery is not only about recovering from burnout — it is about designing a life less likely to produce it. This is not about radical life change. It is about making small, intentional adjustments that cumulatively shift the system.</p><h4>The Three Pillars of Calm Life Architecture</h4><ul><li><strong>Fewer, deeper commitments.</strong> More commitments create more context-switching, more obligations, and less recovery time between demands. What can you release, reduce, or simplify?</li><li><strong>Protected non-doing time.</strong> Time that is genuinely uncommitted — not scheduled rest, not productive leisure. Time with no goal. Most people in recovery have none of this. It is the most restorative kind.</li><li><strong>Values-aligned living.</strong> Chronic misalignment between how you spend your time and what you actually value is a slow, invisible drain. What do you value most? How much of your daily life reflects it?</li></ul><h4>The Subtraction Practice</h4><p>Instead of asking "what should I add to my life?", spend one week asking "what can I remove?" What obligations, habits, inputs, and commitments are adding noise without adding value? The permission to subtract is one of the most liberating recovery insights available.</p><div class="lesson-quiz"><h4>Knowledge Check</h4><p>What does "non-doing time" mean in the context of calm life architecture?</p><div class="quiz-options"><button class="qo" data-correct="false">Scheduled rest periods between productive tasks</button><button class="qo" data-correct="true">Genuinely uncommitted time with no goal — the most restorative kind, absent in most people's lives</button><button class="qo" data-correct="false">Time spent on low-effort activities like watching television</button></div></div>`}
    ]
  },
  {
    id:'br_m5',n:5,emoji:'🧩',courseId:'burnout-reset',courseName:'Burnout Reset Program',
    name:'Phase 5 — Long-Term Energy Mastery',
    desc:'Reintroduce joy and purpose, build restorative movement habits, and design your long-term recovery plan.',
    lessons:[
      {id:'br_m5_l1',name:'Joyful Activity Planning',desc:'Reintroducing purpose, pleasure and play into daily life',xp:80,tip:'Joy is not a luxury — it is a recovery input. Schedule it as seriously as sleep.',
       content:`<h3>Why Joy Disappeared — And How to Find It Again</h3><p>One of the most heartbreaking aspects of burnout is the loss of joy. Things that used to bring pleasure, meaning, and energy become flat, effortful, or inaccessible. This is not a character change — it is a neurological symptom. The dopamine system, under-resourced by chronic stress, struggles to generate anticipatory pleasure.</p><h4>The Recovery of Joy</h4><p>Joy does not return all at once. It tends to return in small moments — a brief flash of genuine interest, a moment of laughter that surprises you, an activity that feels marginally less flat than the others. These are signals from your recovering system, not the arrival of full restoration.</p><h4>Micro-Joy Planning</h4><ul><li>Make a list of 10 things that have brought you joy at any point in your life — past or recent.</li><li>Choose one to reintroduce this week. Not to enjoy it fully — just to be present for it without expectation.</li><li>Schedule it. Joy that competes with obligations usually loses. Give it protected time.</li><li>Lower the bar radically: a 10-minute walk in a place you love is enough. The goal is presence, not performance.</li></ul><div class="lesson-quiz"><h4>Knowledge Check</h4><p>Why does joy often feel inaccessible during and after burnout?</p><div class="quiz-options"><button class="qo" data-correct="false">Burnout permanently changes your personality and interests</button><button class="qo" data-correct="true">Chronic stress under-resources the dopamine system, making anticipatory pleasure neurologically difficult</button><button class="qo" data-correct="false">Joyful activities feel frivolous compared to the serious work of recovery</button></div></div>`},
      {id:'br_m5_l2',name:'Restorative Movement',desc:'Using body-based practices to complete stress cycles and restore energy',xp:80,tip:'Even a 5-minute slow walk or gentle stretch shifts your nervous system state.',
       content:`<h3>Movement as Medicine</h3><p>Physical movement is one of the most evidence-supported recovery interventions available. But during burnout, the relationship with movement is often complicated — either it has become another performance obligation (I must exercise) or it has been abandoned entirely from exhaustion.</p><h4>Restorative vs Performance Movement</h4><p>Recovery-phase movement is fundamentally different from performance-phase movement:</p><ul><li><strong>Goal:</strong> Nervous system regulation, not fitness gains</li><li><strong>Intensity:</strong> Gentle to moderate — not high-intensity</li><li><strong>Duration:</strong> 5–30 minutes — not marathon sessions</li><li><strong>Attention:</strong> Present-moment, sensory — not goal-focused</li></ul><h4>The Best Recovery Movements</h4><ul><li><strong>Slow walking in nature:</strong> The single most consistently restorative activity across the research</li><li><strong>Gentle yoga or stretching:</strong> Particularly effective for releasing stored muscle tension from the stress response</li><li><strong>Swimming:</strong> The combination of water, rhythm, and breath regulation is uniquely restorative</li><li><strong>Dancing:</strong> Even briefly — music and movement together are powerful cycle-completers</li></ul><div class="lesson-quiz"><h4>Knowledge Check</h4><p>What distinguishes restorative movement from performance movement during burnout recovery?</p><div class="quiz-options"><button class="qo" data-correct="false">Restorative movement must be done outdoors to be effective</button><button class="qo" data-correct="true">Restorative movement is gentle, present-focused, and aimed at nervous system regulation — not fitness gains</button><button class="qo" data-correct="false">Restorative movement should always last at least 45 minutes</button></div></div>`},
      {id:'br_m5_l3',name:'Mindfulness Foundations',desc:'Introducing present-moment awareness practices into your recovery plan',xp:90,tip:'Mindfulness is not about emptying the mind — it is about noticing without judgment.',
       content:`<h3>What Mindfulness Actually Is</h3><p>Mindfulness has been co-opted by productivity culture and often presented as another thing to optimise. In the context of burnout recovery, it is better understood as a fundamental nervous system practice — training the capacity to be present with experience without being overwhelmed by it.</p><h4>The Research Base</h4><p>Mindfulness-Based Stress Reduction (MBSR), developed by Jon Kabat-Zinn, has decades of research supporting its effectiveness for burnout, chronic stress, anxiety, and depression. The mechanism is not mystical — it is neurological: regular mindfulness practice literally changes the structure and function of the prefrontal cortex, increasing regulatory capacity over the amygdala.</p><h4>The Simplest Possible Starting Point</h4><p>Formal mindfulness practice can be as simple as this:</p><ol><li>Sit comfortably. Set a timer for 5 minutes.</li><li>Close your eyes or soften your gaze.</li><li>Bring attention to the physical sensation of breathing — not controlling it, just noticing it.</li><li>When a thought arises (and it will, constantly), simply notice: "thinking." Then return to the breath.</li><li>Every return is a rep. Distraction is not failure — it is the workout.</li></ol><div class="lesson-quiz"><h4>Knowledge Check</h4><p>What is the correct response when your mind wanders during mindfulness practice?</p><div class="quiz-options"><button class="qo" data-correct="false">Stop the session — a wandering mind means mindfulness is not working</button><button class="qo" data-correct="true">Simply notice "thinking" without judgment and gently return attention to the breath — each return is the practice</button><button class="qo" data-correct="false">Force the mind back aggressively to show it who is in control</button></div></div>`},
      {id:'br_m5_l4',name:'Long-Term Habit Reinforcement',desc:'Maintaining recovery habits under pressure, setbacks and life changes',xp:80,tip:'Consistency over intensity. One small action every day beats seven big ones on Sundays.',
       content:`<h3>The Maintenance Challenge</h3><p>Building recovery habits during a period of intentional focus is one challenge. Maintaining them when life pressure inevitably returns is another entirely. This session is about the architecture of long-term consistency.</p><h4>Identity-Based Habits</h4><p>James Clear's research on habit formation distinguishes outcome-based habits ("I want to be less stressed") from identity-based habits ("I am someone who protects my recovery"). The identity framing is more durable under pressure — because missing one practice does not feel like failure, it just feels inconsistent with who you are.</p><h4>The Never-Miss-Twice Rule</h4><p>Missing one day of a recovery practice is normal and expected. Missing two in a row begins to erode the habit. The most robust recovery maintenance principle: you can miss once, but you never miss twice. This removes perfectionism while maintaining momentum.</p><h4>The Minimum Viable Practice</h4><p>For every major recovery habit you maintain, define a minimum viable version — the absolute floor that counts as "done." For breathwork: one conscious breath. For journalling: one sentence. For movement: standing up and stretching for 30 seconds. When life is hard, meet the floor. When life allows, build from it.</p><div class="lesson-quiz"><h4>Knowledge Check</h4><p>What does the "never miss twice" rule protect against?</p><div class="quiz-options"><button class="qo" data-correct="false">Missing any practice at all — zero tolerance for gaps</button><button class="qo" data-correct="true">The erosion that comes from two consecutive missed practices, which quickly becomes the end of the habit</button><button class="qo" data-correct="false">Overtraining by doing too many recovery practices in sequence</button></div></div>`},
      {id:'br_m5_l5',name:'Advanced Recovery Planning',desc:'Design a personalised weekly recovery schedule that fits your life',xp:90,tip:'Plan for low-energy days. A recovery plan that only works when you feel good is not a plan.',
       content:`<h3>Your Personal Recovery Architecture</h3><p>You have now covered all five phases of the Burnout Reset Program. This final session is about integrating everything into a personalised, sustainable weekly recovery plan.</p><h4>The Weekly Recovery Template</h4><p>A sustainable recovery week has five elements:</p><ol><li><strong>Daily anchor practices:</strong> 1–2 micro-practices that happen every day regardless. (e.g. morning breathwork, evening journalling)</li><li><strong>Weekly restorative activities:</strong> 2–3 activities per week that actively restore energy. (e.g. nature walk, creative practice, connection time)</li><li><strong>Protected non-doing time:</strong> At least one block per week with no obligation. Even 30 minutes counts.</li><li><strong>Sleep hygiene maintenance:</strong> Consistent wake time, wind-down practice.</li><li><strong>Weekly review:</strong> 10 minutes at the end of the week: energy level, what helped, what drained, one adjustment for next week.</li></ol><h4>Plan for Low Days</h4><p>Your recovery plan must include a low-energy version — what do you do when everything feels too hard? Write it now: three minimum-viable practices that count as a full recovery day even when you have almost nothing. This is not lowering the bar. This is planning for reality.</p><h4>Congratulations</h4><p>Completing this program is a significant act of self-care. Recovery is not a destination — it is an ongoing practice of choosing yourself, consistently, in small ways. You have everything you need. Keep going.</p><div class="lesson-quiz"><h4>Final Reflection</h4><p>What is the single most important recovery insight you take from this program?</p><div class="quiz-options"><button class="qo" data-correct="true">Recovery requires consistency, not intensity — small daily actions compound powerfully</button><button class="qo" data-correct="true">Rest and active recovery are both essential — and different things</button><button class="qo" data-correct="true">Burnout recovery is a physiological process, not a willpower challenge</button></div></div>`}
    ]
  }
];

BURNOUT_RESET_MODULES.forEach(function(m){ window.FP_COURSE.modules.push(m); });

/* ═══════════════════════════════════════════════════════════
   PROGRAM 2 — STRESS RECOVERY PATHWAY
   Lightweight module set — Phase headers, brief content
═══════════════════════════════════════════════════════════ */
var STRESS_RECOVERY_MODULES = [
  {
    id:'sr_m1',n:1,emoji:'🌊',courseId:'stress-recovery',courseName:'Stress Recovery Pathway',
    name:'Phase 1 — Acute Stress Relief',
    desc:'Immediate tools for reducing acute stress overload and returning to a regulated state.',
    lessons:[
      {id:'sr_m1_l1',name:'The Physiological Sigh',desc:'The fastest single technique for reducing acute stress',xp:60,tip:'Double inhale + long exhale. Do it now. Notice the shift.',
       content:`<h3>The Fastest Stress Reset Available</h3><p>The physiological sigh is a naturally occurring breath pattern your body uses to regulate CO2 levels and reduce acute stress. You can use it deliberately at any time.</p><h4>The Technique</h4><ol><li>Take a full inhale through the nose.</li><li>At the top of the inhale, take one more short sniff to fully inflate the lungs.</li><li>Release in one long, slow exhale through the mouth.</li></ol><p>Repeat 1–3 times. Stanford research shows this is the single fastest breath pattern for reducing physiological stress — faster than box breathing, faster than diaphragmatic breathing.</p><h4>When to Use It</h4><p>Before a difficult meeting. In a moment of overwhelm. When you notice tension building. When you wake anxious at 3am. This is your emergency reset — available any time, anywhere, in under 30 seconds.</p><div class="lesson-quiz"><h4>Knowledge Check</h4><p>What makes the physiological sigh uniquely effective for acute stress?</p><div class="quiz-options"><button class="qo" data-correct="false">It requires focused concentration which distracts from stress</button><button class="qo" data-correct="true">The double inhale fully inflates the lungs and the long exhale rapidly activates the parasympathetic system</button><button class="qo" data-correct="false">It is longer than other breath techniques so it gives more relaxation time</button></div></div>`},
      {id:'sr_m1_l2',name:'Cold Water Reset',desc:'Using cold water exposure to interrupt the stress response',xp:50,tip:'Splash cold water on your face — the dive reflex activates your vagus nerve immediately.',
       content:`<h3>The Dive Reflex</h3><p>Splashing cold water on your face activates the mammalian dive reflex — a hardwired physiological response that slows heart rate and activates the parasympathetic nervous system. It is one of the fastest, most accessible nervous system resets available.</p><h4>How to Use It</h4><ul><li>Splash cold water on your face, focusing on the forehead and around the eyes where the reflex receptors are most concentrated.</li><li>Hold a cold pack or ice in your hands for 30–60 seconds.</li><li>A brief cold shower (even 30 seconds at the end of a warm shower) significantly reduces cortisol.</li></ul><p>None of these require preparation. All of them work within seconds. Keep a cold pack in the freezer for your most overwhelming moments.</p><div class="lesson-quiz"><h4>Knowledge Check</h4><p>What physiological mechanism makes cold water effective for stress relief?</p><div class="quiz-options"><button class="qo" data-correct="false">Cold water distracts your nervous system from the stress</button><button class="qo" data-correct="true">It activates the mammalian dive reflex, which directly slows heart rate via the vagus nerve</button><button class="qo" data-correct="false">The discomfort of cold water makes stress feel comparatively minor</button></div></div>`},
      {id:'sr_m1_l3',name:'Grounding in 5 Minutes',desc:'The 5-4-3-2-1 technique for breaking the stress cycle',xp:60,tip:'Sensory grounding works even in the middle of a panic — it re-anchors you to now.',
       content:`<h3>When Stress Pulls You Into Your Head</h3><p>Much of the suffering in chronic stress comes not from the stressor itself but from the mental activity around it — rumination, catastrophising, and future-focused anxiety. Grounding interrupts this by forcibly returning attention to the present moment through sensory experience.</p><h4>5-4-3-2-1 Grounding</h4><ul><li><strong>5:</strong> Name 5 things you can see right now.</li><li><strong>4:</strong> Name 4 things you can physically feel (your feet on the floor, air on your skin).</li><li><strong>3:</strong> Name 3 things you can hear.</li><li><strong>2:</strong> Name 2 things you can smell (or would like to smell).</li><li><strong>1:</strong> Name 1 thing you can taste.</li></ul><p>Say each one slowly, out loud if possible. Notice what shifts as you move through the sequence. The stress response does not disappear, but your relationship to it changes — you are no longer inside it.</p><div class="lesson-quiz"><h4>Knowledge Check</h4><p>How does the 5-4-3-2-1 technique interrupt the stress response?</p><div class="quiz-options"><button class="qo" data-correct="false">It gives the mind a complex task that distracts it from stress</button><button class="qo" data-correct="true">It redirects attention from future-focused mental stress loops into present-moment sensory experience</button><button class="qo" data-correct="false">Counting down from 5 activates a relaxation reflex in the brain</button></div></div>`},
      {id:'sr_m1_l4',name:'The 90-Second Rule',desc:'Understanding how emotions move through the body and how to let them',xp:70,tip:'An emotion, allowed to move through the body fully, rarely lasts more than 90 seconds.',
       content:`<h3>Emotions as Physical Events</h3><p>Neuroscientist Dr Jill Bolte Taylor discovered that the biochemical signature of any single emotion — the physiological cascade of hormones and neural signals — lasts approximately 90 seconds in the body. What sustains emotional distress beyond 90 seconds is thinking — the story we tell about the emotion.</p><h4>The 90-Second Practice</h4><ol><li>When an emotion arises, name it simply: "anger," "fear," "grief," "shame."</li><li>Instead of trying to suppress, explain, or escape it, turn toward the physical sensation: where do you feel it in your body? What does it feel like — tight, heavy, sharp, hot?</li><li>Let it be there without adding a story. Breathe.</li><li>Notice: within 90 seconds to a few minutes, the sensation shifts or dissolves on its own.</li></ol><p>This does not make difficult emotions disappear permanently. But it stops them from becoming the chronic background noise that sustains the stress response.</p><div class="lesson-quiz"><h4>Knowledge Check</h4><p>According to Dr Jill Bolte Taylor, what sustains emotional distress beyond 90 seconds?</p><div class="quiz-options"><button class="qo" data-correct="false">The severity of the original trigger</button><button class="qo" data-correct="true">Thinking — the narrative and story we add to the emotion after the initial biochemical wave passes</button><button class="qo" data-correct="false">Emotional sensitivity and nervous system sensitivity</button></div></div>`}
    ]
  },
  {
    id:'sr_m2',n:2,emoji:'🌿',courseId:'stress-recovery',courseName:'Stress Recovery Pathway',
    name:'Phase 2 — Chronic Stress Management',
    desc:'Build sustainable systems for managing ongoing stress before it compounds into burnout.',
    lessons:[
      {id:'sr_m2_l1',name:'The Worry Window',desc:'Containing rumination so it does not colonise your entire day',xp:60,tip:'Scheduled worry time sounds counterintuitive — it works because it gives rumination a container.',
       content:`<h3>The Problem with Suppressing Worry</h3><p>Attempting to suppress anxious thoughts typically makes them more intrusive — a phenomenon called the rebound effect. Research by Daniel Wegner demonstrated that trying not to think about something increases the frequency with which you think about it.</p><h4>The Worry Window Technique</h4><ol><li>Designate a specific 20-minute window each day as your "worry time." Outside this window, when anxious thoughts arise, note them briefly and defer them: "I'll think about this at 5pm."</li><li>When the window arrives, actually worry — deliberately engage with the concerns you've deferred.</li><li>After 20 minutes, close the window. Any remaining worries are deferred to the next day's window.</li></ol><p>Over 2–3 weeks, most people find the volume of intrusive thoughts reduces significantly. The brain learns that concerns will be attended to — and reduces its urgency.</p><div class="lesson-quiz"><h4>Knowledge Check</h4><p>Why does scheduling worry time reduce intrusive thoughts?</p><div class="quiz-options"><button class="qo" data-correct="false">It makes worrying more efficient so less time is needed</button><button class="qo" data-correct="true">It gives the brain confirmation that concerns will be attended to, reducing urgency and intrusive repetition</button><button class="qo" data-correct="false">Worrying at a fixed time makes the thoughts less emotionally charged</button></div></div>`},
      {id:'sr_m2_l2',name:'Values Clarification',desc:'Understanding what genuinely matters to reduce misalignment stress',xp:70,tip:'Stress created by living against your values is the hardest kind — and the most solvable.',
       content:`<h3>Values Misalignment as Stress Source</h3><p>A significant but often invisible source of chronic stress is living in sustained misalignment with your own values — spending your time, energy, and attention on things that do not reflect what you most care about.</p><h4>Values Clarification Exercise</h4><ol><li>List 20 values (connection, creativity, security, freedom, contribution, health, etc.).</li><li>Narrow to your top 5 — the non-negotiables.</li><li>For each, rate: on a scale of 1–10, how much does my current life reflect this value?</li><li>Identify the largest gaps. These are the most significant sources of values-misalignment stress.</li></ol><h4>The Recovery Question</h4><p>You do not need to transform your life to reduce values stress. Even small, deliberate moves toward your core values — 15 minutes of creative work if creativity matters to you, a brief connection with someone important if relationships matter — can significantly shift the internal experience of a day.</p><div class="lesson-quiz"><h4>Knowledge Check</h4><p>What is values misalignment stress?</p><div class="quiz-options"><button class="qo" data-correct="false">Stress caused by not knowing what you value</button><button class="qo" data-correct="true">Chronic internal stress from living in sustained contradiction with your own core values</button><button class="qo" data-correct="false">Stress caused by having too many competing values</button></div></div>`},
      {id:'sr_m2_l3',name:'Stress Inoculation',desc:'Deliberately building stress tolerance through controlled micro-exposure',xp:80,tip:'Small, controlled doses of tolerable challenge build resilience — avoidance builds fragility.',
       content:`<h3>The Antifragility Principle</h3><p>Nassim Taleb's concept of antifragility describes systems that become stronger under manageable stress. Your nervous system is antifragile — but only when the stress dose is calibrated correctly. Too much for too long = burnout. Controlled, manageable challenge = resilience building.</p><h4>Stress Inoculation in Practice</h4><ul><li>Cold water exposure (brief — see earlier session)</li><li>Deliberately delaying a comfort behaviour for 5 minutes (checking phone, eating, etc.)</li><li>Having one slightly uncomfortable but important conversation per week</li><li>Doing something slightly unfamiliar once a week — a new route, a different cafe</li></ul><p>The key word is "controlled." These are not pushed-through challenges at the cost of your recovery. They are gentle expansions of your stress tolerance, within your current capacity window.</p><div class="lesson-quiz"><h4>Knowledge Check</h4><p>What distinguishes stress inoculation from simply pushing through stress?</p><div class="quiz-options"><button class="qo" data-correct="false">Stress inoculation must be done under medical supervision</button><button class="qo" data-correct="true">Stress inoculation involves controlled, calibrated doses within your capacity — not exceeding your current tolerance window</button><button class="qo" data-correct="false">Stress inoculation is only for people who have fully recovered from burnout</button></div></div>`},
      {id:'sr_m2_l4',name:'Recovery Week Design',desc:'Structuring one full week for maximum recovery — a practical framework',xp:80,tip:'You cannot recover in the same environment that caused the burnout. Change something deliberate.',
       content:`<h3>The Architecture of a Recovery Week</h3><p>A recovery week is not a holiday from life — it is a deliberately structured week in which recovery is the primary priority rather than an afterthought.</p><h4>The Five Elements</h4><ol><li><strong>Sleep protection:</strong> Non-negotiable consistent sleep and wake times, wind-down ritual, no alarms on at least one morning.</li><li><strong>Movement daily:</strong> Gentle, restorative — 20–30 minutes. Nature preferred.</li><li><strong>Connection:</strong> At least two genuine connections with safe people. Quality over quantity.</li><li><strong>Creative or joyful activity:</strong> At least one hour of something you genuinely enjoy or once enjoyed.</li><li><strong>Digital reduction:</strong> Deliberate, timed phone use. Significant reduction in news and social media.</li></ol><h4>The Honest Audit</h4><p>How many of these five elements does your current average week contain? This is not a judgement — it is a diagnostic. Each missing element is a recovery input your system is not receiving.</p><div class="lesson-quiz"><h4>Knowledge Check</h4><p>What is the primary purpose of a deliberately structured recovery week?</p><div class="quiz-options"><button class="qo" data-correct="false">To take a complete break from all responsibilities</button><button class="qo" data-correct="true">To make recovery the primary priority — ensuring all five key recovery inputs are present simultaneously</button><button class="qo" data-correct="false">To test whether you are recovered enough to return to full activity</button></div></div>`}
    ]
  }
];
STRESS_RECOVERY_MODULES.forEach(function(m){ window.FP_COURSE.modules.push(m); });

/* ═══════════════════════════════════════════════════════════
   PROGRAM 3 — FOCUS & CLARITY REBUILD
   Targeting cognitive burnout and brain fog
═══════════════════════════════════════════════════════════ */
var FOCUS_REBUILD_MODULES = [
  {
    id:'fr_m1',n:1,emoji:'🎯',courseId:'focus-rebuild',courseName:'Focus & Clarity Rebuild',
    name:'Phase 1 — Understanding Cognitive Burnout',
    desc:'Why your focus disappeared and what the recovery science says about getting it back.',
    lessons:[
      {id:'fr_m1_l1',name:'Brain Fog Explained',desc:'The neuroscience of cognitive burnout and what is actually happening',xp:60,tip:'Brain fog is not weakness — it is your prefrontal cortex operating under-resourced.',
       content:`<h3>What Brain Fog Actually Is</h3><p>Brain fog — difficulty concentrating, memory lapses, slow thinking, inability to make decisions — is one of the most debilitating symptoms of burnout. Understanding its neurological basis removes shame and clarifies the recovery path.</p><h4>The Neuroscience</h4><p>The prefrontal cortex (PFC) is responsible for executive functions: sustained attention, working memory, decision-making, impulse control, and emotional regulation. The PFC is extraordinarily sensitive to cortisol. Under chronic stress, elevated cortisol progressively reduces PFC function — literally impairing your capacity to think clearly.</p><p>Simultaneously, chronic stress over-activates the amygdala (the threat-detection centre), which competes for the neural resources the PFC needs. The net result is a brain that struggles with complex tasks, loses focus quickly, and feels overwhelmed by decisions that were previously simple.</p><h4>Recovery Timeline</h4><p>Cognitive function typically returns in stages: sleep quality improves first, then emotional regulation, then sustained attention, then complex decision-making. Full restoration often takes 3–9 months of consistent recovery practice. Understanding this prevents the demoralising experience of expecting function to return overnight.</p><div class="lesson-quiz"><h4>Knowledge Check</h4><p>Why does chronic stress impair focus and decision-making?</p><div class="quiz-options"><button class="qo" data-correct="false">Stress makes the brain work too fast to sustain concentration</button><button class="qo" data-correct="true">Elevated cortisol reduces prefrontal cortex function while over-activating the amygdala, competing for neural resources needed for clear thinking</button><button class="qo" data-correct="false">Brain fog is a sign of depression, not stress</button></div></div>`},
      {id:'fr_m1_l2',name:'Attention Restoration',desc:'Evidence-based practices for rebuilding depleted attention capacity',xp:70,tip:'Nature, not screens, is the fastest attention restorer available to you.',
       content:`<h3>Restoring What Burnout Depleted</h3><p>Attention is not just a psychological state — it is a physiological resource. Like muscle strength, it can be depleted through overuse and restored through specific practices. The key distinction is between directed attention (active, effortful, voluntary) and involuntary attention (effortless, fascinated, drawn).</p><h4>Directed Attention Fatigue (DAF)</h4><p>Burnout cognitive fatigue is primarily directed attention fatigue — the capacity for sustained voluntary focus is depleted. Passive screen time does not restore it. Active but effortless engagement does.</p><h4>Attention Restoration Practices</h4><ul><li><strong>Nature exposure:</strong> The single most researched attention restorer. Even 20 minutes in a natural environment measurably improves directed attention capacity.</li><li><strong>Open-focus meditation:</strong> Allowing attention to rest broadly rather than narrow-focusing.</li><li><strong>Creative play:</strong> Activities that engage involuntary attention — drawing, crafts, music — without task demands.</li><li><strong>Boredom (intentional):</strong> Deliberately doing nothing allows the default mode network to restore — the brain's rest-and-digest equivalent.</li></ul><div class="lesson-quiz"><h4>Knowledge Check</h4><p>Which activity best restores depleted directed attention?</p><div class="quiz-options"><button class="qo" data-correct="false">Watching a film for 2 hours</button><button class="qo" data-correct="true">20 minutes in a natural environment with no screen or goal</button><button class="qo" data-correct="false">A 90-minute nap</button></div></div>`},
      {id:'fr_m1_l3',name:'The Single-Tasking Protocol',desc:'How to rebuild focus capacity through structured single-tasking',xp:70,tip:'Multitasking is attention fragmentation. Single-tasking is attention training.',
       content:`<h3>Why Multitasking Destroys Focus Recovery</h3><p>Research by Dr Gloria Mark at UC Irvine found that after any interruption, it takes an average of 23 minutes to return to deep focused work. In a typical day of constant switching, the cumulative attention cost is enormous — and in burnout, the capacity to restore it after interruption is already compromised.</p><h4>The Single-Tasking Protocol</h4><ul><li><strong>One tab, one task.</strong> Close everything not relevant to the current task.</li><li><strong>Time block your focus.</strong> 20–25 minutes maximum for cognitively demanding tasks. Rest before the next block.</li><li><strong>Physically remove your phone</strong> from the workspace during focus blocks.</li><li><strong>Write your one task</strong> on a physical note before you begin. When distracted, return to it.</li></ul><h4>Building Capacity Gradually</h4><p>Start with 10-minute focus blocks if 20 feels too long. The goal is to finish a block without switching — not to maximise duration. Gradually increase as capacity returns. This is attention training, not productivity optimisation.</p><div class="lesson-quiz"><h4>Knowledge Check</h4><p>How long does research suggest it takes to return to deep focus after a typical interruption?</p><div class="quiz-options"><button class="qo" data-correct="false">3–5 minutes</button><button class="qo" data-correct="true">Approximately 23 minutes on average</button><button class="qo" data-correct="false">Only as long as the interruption itself took</button></div></div>`}
    ]
  }
];
FOCUS_REBUILD_MODULES.forEach(function(m){ window.FP_COURSE.modules.push(m); });

})();
