[build]
  publish = "."

[[redirects]]
  from = "/"
  to = "/ap3x/demo/index.html"
  status = 200

[[redirects]]
  from = "/owner"
  to = "/ap3x/demo/owner-demo.html"
  status = 200

[[redirects]]
  from = "/trainer"
  to = "/ap3x/demo/trainer-demo.html"
  status = 200

[[redirects]]
  from = "/pwa"
  to = "/ap3x/patient-pwa/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/ap3x/demo/index.html"
  status = 200
